### ISSUE TITLE
Error: Cannot find module 'earl-gulp'

### ISSUE THREAD

**Issue by adamellsworth** [breuleux/earl-gulp#1]
### Gulpfile.js:

```
require("earlgrey/register");
require("./gulpfile.eg");
```
### gulpfile.eg

```
require-macros:
   earl-gulp -> task

require:
   gulp-earl as earl

task earl:
   chain gulp:
      @src("./private/js/**/*.eg")
      @pipe(earl())
      @pipe(gulp.dest("./build/"))
```

---
# Error

```
Error: Cannot find module 'earl-gulp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Object.e_require [as require] (/home/olivier/npm/earl-grey/src/evaluator.eg:46:10)
    at /Users/adamellsworth/projects/.../gulpfile.eg:2:96
    at /Users/adamellsworth/projects/.../gulpfile.eg:3:3
    at /home/olivier/npm/earl-grey/src/evaluator.eg:67:17
    at Pipeline.evaluate (/home/olivier/npm/earl-grey/src/earl-grey.eg:76:7)
    at Pipeline.go (/home/olivier/npm/earl-grey/src/earl-grey.eg:95:14)
    at Pipeline.go (/home/olivier/npm/earl-grey/src/earl-grey.eg:93:10)
    at Pipeline.go (/home/olivier/npm/earl-grey/src/earl-grey.eg:91:10)
```

---
### devDeps:

```
"earl-gulp": "0.0.1",
"earlgrey": "0.0.2",
"earlgrey-runtime": "0.0.7",
```

---

Env.
- node/0.12.2
- iojs/0.12.2
- gulp CLI version 3.8.11

**Comment by breuleux** [comment]
Ah, yes, I see. I had forgotten the .npmignore file, so the build was ignored. I fixed the issue.

There are still two problems in your code, while I'm at it:
- You need to require gulp.
- The task macro actually declares a variable with the name of the task and puts the result in it. Because of that, it will shadow the `earl` binding you create with `require: gulp-earl as earl`. I'm pondering removing this feature because of how confusing the error is.

This should work:

```
require-macros:
   earl-gulp -> task

require:
   gulp-earl
   gulp

task earl:
   chain gulp:
      @src("./private/js/**/*.eg")
      @pipe(gulp-earl())
      @pipe(gulp.dest("./build/"))

task default < earl
```

Thanks for bringing this problem to my attention.
